name: Auto Import NSE MTF (1-week lag)

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch MTF CSV from NSE
        run: python fetch_csv.py

      - name: Process CSV and Upload to Google Sheets
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python process_and_upload.py

      - name: Commit CSV to Repository
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "MTF data added for $(date -d '7 days ago' +'%d-%b-%Y')" || echo "No changes to commit"
          git push

